spring:
  application:
    name: hub-router

server:
  port: 8085

grpc:
  server:
    port: 59090
    enableKeepAlive: true
    keepAliveTime: 30s
    keepAliveTimeout: 10s
    reflection-service-enabled: true

logging:
  level:
    ru.yandex.practicum.kafka.telemetry: INFO

